### ISSUE TITLE
Capture turn around time for PRs that are merged

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#143]
When a PR is merged, the turnaround time for it is to be computed. It is the time taken from when the linked issue is assigned to the PR author to when it was merged.

### Tasks
- [ ] Compute and store the turn around time of merged PRs in the JSON data
- [ ] Show the turn around time for the PR event
- [ ] Show the avg. turn around time of a contributor in contributor profile
