### ISSUE TITLE
Improvements to leaderboard dev. experience

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#152]
## Tasks

- [x] Remove static data from `coronasafe/leaderboard` repo and git ignore `data` and `contributors` directory (and any other directories that has static data by the scraper)
- [x] Vercel preview deploys to use data from `coronasafe/leaderboard-data` repo.
- [x] Add npm that'll fetch static data from data repo for local development.

```bash
export LEADERBOARD_DATA_REPO=https://github.com/coronasafe/leaderboard-data
pnpm run prepare
```
