### ISSUE TITLE
Support for tracking commits pushed directly to default branch

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#218]
## Problem

In certain cases, contributions are made to a project by directly pushing a commit to the repository's default branch. Leaderboard currently does not track such activities performed by the contributor.

## Action Items

- [ ] Update scrapper to track commits pushed to a branch by a contributor. Tag those activities if it was made to the default branch or not.
- [ ] Update the contributor page to reflect the new information being captured.
- [ ] Update the leaderboard page to show commits made to the default branches and support sorting by the same.
