### ISSUE TITLE
Configurable secondary color

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#303]
### Problem Statement
Currently, the secondary color is not configurable in the leaderboard.

### Tasks

- [ ] Add CSS Variables for a configurable secondary color to the `theme.css` (in the data repo https://github.com/coronasafe/leaderboard-data/blob/main/config/theme.css)
- [ ] The secondary color for gray in the data repo should be Tailwind's gray color
- [ ] Update tailwind config to extend to have a secondary color palette that uses the newly defined CSS variables
- [ ] Replace all usages of tailwind's gray color such as `bg-gray-***`, `text-gray-***`, `border-gray-***`, etc. with `bg-secondary-***`, etc.

**Comment by HARSHDOIPHODE** [comment]
please assign me this issue

**Comment by HARSHDOIPHODE** [comment]
@rithviknishad please check and let me know if any changes are needed.

**Comment by rithviknishad** [comment]
Kindly link the issue with a closing tag @HARSHDOIPHODE

**Comment by HARSHDOIPHODE** [comment]
This PR resolves issue #303.

Closes #303
